module.exports = [
  require('./guess-a-number'),
  require('./opinion'),
  require('./dagestan'),
  require('./coin'),
  require('./affirmative'),
  require('./hello'),
  require('./daaaaa'),
  require('./default'), 
  require('./localmems/Tolstoy'), 
  require('./localmems/bot1'),
  require('./localmems/subscribers'),
  require('./localmems/5'),
  require('./localmems/Night'),
  require('./localmems/rudeness'),
];
